# triggers_pipeline.yaml
# This is yaml file that will triggers the pipeline on changes to the specified branches(main in this example) while
# excluding certaine files and folders(readme.md and docs/* in this example)

stages:
  - stage: 
    jobs:
      - job: TriggerJob
        displayName: "triggers the first pipeline"
        pool:
         
          
        steps:
            - task: Maven@4
              inputs:
                  mavenPomFile: 'pom.xml'
                  publishJUnitResults: true
                  testResultsFiles: '**/surefire-reports/TEST-*.xml'
                  javaHomeOption: 'JDKVersion'
                  mavenVersionOption: 'Default'
                  mavenAuthenticateFeed: false
                  effectivePomSkip: false
                  sonarQubeRunAnalysis: true
                  sqMavenPluginVersionChoice: 'latest'
                  checkStyleRunAnalysis: true
                  pmdRunAnalysis: true
                  findBugsRunAnalysis: true
                  spotBugsRunAnalysis: true
trigger:
 branches:
    include:
    - main
 paths:
   exclude:
     - README.md
     - docs/*
